---
title: My R Take on Advent of Code - Day 4
author: Kasia Kulma
date: '2019-01-05'
slug: advent-of-code-day-4
categories:
  - r
tags:
  - tidyverse
description: ''
topics: []
draft: true
---


```{r, warning=FALSE, message=FALSE}
library(tidyverse)
```


```{r}
raw_input <- read.delim('day4-raw-input.txt', header = F)
head(raw_input)
```

```{r}
# clean the input
clean_input <- raw_input %>%
  rename(value = V1) %>% 
  mutate(timestamp = ymd_hm(str_extract(value, '[:digit:]+-[:digit:]+-[:digit:]+..[:digit:]+:[:digit:]+')),
         action = str_extract(value, '[:alpha:]+..[:alpha:]+'),
         guard_num = ifelse(str_detect(value, '#'), str_extract(value, '#[:digit:]+'), NA),
         date = ymd(str_sub(timestamp, start = 1, end = 10)),
         minute = minute(timestamp)
  ) %>%
  arrange(timestamp) %>% 
  fill(guard_num) # fill in missing guard numbers 

head(clean_input)
```


```{r}
# who sleeps most 
clean_input %>% 
  filter(action != 'Guard') %>%
  group_by(guard_num, date) %>% 
  mutate(time_asleep = ifelse(action == 'wakes up', minute - lag(minute), NA ) #calculate time asleep
  ) %>% 
  group_by(guard_num) %>% 
  na.omit() %>% 
  summarise(total_asleep = sum(time_asleep)) %>%  # sum it
  arrange(desc(total_asleep)) %>% 
  slice(1)
```
  
```{r}
# what's the most common time to sleep

guard_data <- clean_input %>% 
  filter(action != 'Guard') %>% 
  filter(guard_num == '#409') %>% # pick the winner
  arrange(timestamp) %>% 
  spread(action, minute) %>% # prep the data for sequences
  rename(falls_asleep = `falls asleep`,
         wakes_up = `wakes up`) %>% 
  mutate(falls_asleep = ifelse(!is.na(wakes_up), lag(falls_asleep), falls_asleep )) %>% 
  na.omit()

head(guard_data)
```


```{r}
# function that generates sequence of minutes between falling asslep and waking up  
time_seq <- function(falls, wakes) {
  result <- seq(falls, wakes)
  return(result)
}
```

```{r}
# test the function
time_seq(guard_data$falls_asleep[1], guard_data$wakes_up[1])
```

```{r}
# apply the funtion to the #409 guard's data
pmap(list(guard_data$falls_asleep,
          guard_data$wakes_up
          ), time_seq) %>% 
  unlist() %>% 
  table() %>% 
  sort() # three potential answers! the middle one is correct@
```

```{r}
# final solution
409*51
```